- name: Installing Docker
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - containerd
    - docker.io

- name: Configuring Docker autostart
  service: name=docker enabled=yes state=started masked=no
