- name: Apache web server(s) uninstall
  become: yes
  hosts: nodes
  gather_facts: false

  tasks:
    - name: Uninstall httpd
      yum: name=httpd state=absent

    - name: Delete index.html
      file:
        path: /var/www/html/index.html
        state: absent
      
    - name: Disable http traffic
      firewalld:
        service: http
        permanent: yes
        immediate: yes
        state: disabled

