- name: Apache web server(s) setup
  become: yes
  hosts: nodes
  gather_facts: false

  tasks:
    - name: Install firewall
      yum: name=firewalld state=present
      
    - name: Configure firewall autostart
      systemd: name=firewalld enabled=yes state=started masked=no

    - name: Allow http traffic
      firewalld:
        service: http
        permanent: yes
        immediate: yes
        state: enabled

    - name: Install httpd
      yum: name=httpd state=present
      
    - name: Configure httpd autostart
      systemd: name=httpd enabled=yes state=started masked=no

    - name: Create index.html
      copy:
        src: index.html
        dest: /var/www/html/index.html

    
