- name: Install httpd
  yum: name=httpd state=present
  
- name: Configure httpd autostart
  systemd: name=httpd enabled=yes state=started masked=no

- name: Create index.html
  template:
    src: index.html.j2
    dest: "{{ www_root }}/index.html"

#- name: debug
#  debug: var=firewall_services

- name: Allow web traffic
  firewalld:
    service: "{{ item }}"
    permanent: yes
    immediate: yes
    state: enabled
  loop: "{{ firewall_services }}"
    
