---
- name: Grub config
  become: yes
  hosts: nodes
  gather_facts: false
  vars:
    grub_file: "/etc/default/grub"
#    grub_file: "/tmp/grub"

  tasks:
    - name: Append 'biosdevname' if absent 
      lineinfile:
        path: "{{ grub_file }}"
        regexp: '^(GRUB_CMDLINE_LINUX="(?:(?!biosdevname).)*?)"$'
        line: '\1 biosdevname=0"'
        backrefs: yes
      register: biosdevname
#    - debug: var=biosdevname

    - name: Set correct 'biosdevname' value
      when: not biosdevname.changed
      lineinfile:
        path: "{{ grub_file }}"
        regexp: '^(GRUB_CMDLINE_LINUX=".*)biosdevname=[^0](.*)"$'
        line: '\1biosdevname=0\2"'
        backrefs: yes


    - name: Append 'net.ifnames' if absent 
      lineinfile:
        path: "{{ grub_file }}"
        regexp: '^(GRUB_CMDLINE_LINUX="(?:(?!net\.ifnames).)*?)"$'
        line: '\1 net.ifnames=0"'
        backrefs: yes
      register: ifnames

    - name: Set correct 'net.ifnames' value
      when: not ifnames.changed
      lineinfile:
        path: "{{ grub_file }}"
        regexp: '^(GRUB_CMDLINE_LINUX=".*)net\.ifnames=[^0](.*)"$'
        line: '\1net.ifnames=0\2"'
        backrefs: yes

    - name: Generate a GRUB configuration file
      shell:
        cmd: grub2-mkconfig

