# Installing app 
- name: Creating app folder
  ansible.builtin.file:
    path: "{{ app_path }}"
    state: directory
    mode: "02775"
    owner: "{{ app_user }}"
    group : "{{ app_user }}"

- name: Untar app
  unarchive:
    src: ./.files/ldap_auth_service.tgz
    dest: /opt  #"{{ app_path }}"
    owner: "{{ app_user }}"
    group : "{{ app_user }}"
