---
- name: Install software
  gather_facts: false
  hosts: all
  
  tasks:
  - name: Install common software
    apt:
      name: "{{ packages }}"
    vars:
      packages:
      - net-tools
      - dnsutils
      - nfs-common
      - postgresql-client
      - curl
      - wget
      - tcpdump
      - dialog
      - sshfs
      - rsync
  #    - nmap  # absent in Astra Linux
