---
- name: Install software
  gather_facts: true
  hosts: all
  vars:
    packages:
      - net-tools
      - nfs-common
      # - postgresql-client
      - curl
      - wget
      - tcpdump
      - sshfs
      - rsync
      - tree
      - ntp
      - zabbix-agent
      # - dialog  # not needed for a while
      # - nmap  # absent in Astra Linux
    packages_deb:
      - dnsutils
    packages_rhel:
      - bind-utils
      

  tasks:
  - name: Printing OS Family
    ansible.builtin.debug:
      # var: ansible_facts['distribution']
      var: ansible_facts['os_family']

  - name: Installing packages by apt
    apt:
      name: "{{ item }}"
      update_cache: yes
    loop: "{{ packages }}"
    when: ansible_facts['os_family'] in ["Debian", "Astra Linux"]

  - name: Installing packages by dnf
    ansible.builtin.dnf:
      name: "{{ item }}"
      # update_cache: yes
    loop: "{{ packages }}"
    when: ansible_facts['os_family'] == "RedHat"

  - name: Configuring ntp daemon
    ansible.builtin.systemd:
      name: ntp
      enabled: yes
      masked: no
      state: started

  - name: Configuring zabbix-agent daemon
    ansible.builtin.systemd:
      name: zabbix-agent
      enabled: yes
      masked: no
      state: started
