---
- name: Install Docker play
  hosts: all
  gather_facts: true
  become: true
  # vars:

  tasks:
    - name: Printing OS Family
      ansible.builtin.debug:
        # var: ansible_facts['distribution']
        var: ansible_facts['os_family']


    - name: Uninstalling old versions (RHEL)
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: absent
      loop:
        - docker
        - docker-client
        - docker-client-latest
        - docker-common
        - docker-latest
        - docker-latest-logrotate
        - docker-logrotate
        - docker-engine
      when: ansible_facts['os_family'] == "RedHat"

    - name: Uninstalling old versions (Debian)
      ansible.builtin.apt:
        name: "{{ item }}"
        state: absent
      loop:
        - docker.io
        - docker-compose
        - docker-compose-v2
        - docker-doc
        - podman-docker
      when: ansible_facts['os_family'] in ["Debian" ]

    - name: Installing requied packages (RHEL)
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: present
      loop:
        - gnupg2
      when: ansible_facts['os_family'] == "RedHat"

    - name: Installing requied packages (Debian)
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        update_cache: true
      loop:
        - ca-certificates
        - curl
        - gnupg
      when: ansible_facts['os_family'] in ["Debian" ]

    - name: Add Docker's official GPG key
      ansible.builtin.shell: |
        install -m 0755 -d /etc/apt/keyrings
        curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
        chmod a+r /etc/apt/keyrings/docker.gpg

    - name: Add the repository to Apt sources
      ansible.builtin.shell: |
        echo \
          "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian \
          "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | \
          tee /etc/apt/sources.list.d/docker.list > /dev/null

    - name: Installing Docker (Debian)
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        update_cache: true
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin
      when: ansible_facts['os_family'] in ["Debian" ]

