---
- name: Install Docker play
  hosts: all 
  gather_facts: true
  become: true
  vars:

  tasks:
    - name: Printing OS Family
      ansible.builtin.debug:
        # var: ansible_facts['distribution']
        var: ansible_facts['os_family']

    - name: Uninstalling old versions (RHEL)
      ansible.builtin.dnf:
        name: 
        state: present
      when: ansible_facts['os_family'] == "RedHat"

    # Debian
    - name: Uninstalling old versions (Debian)
      ansible.builtin.apt:
        name: "{{ item }}"
        state: absent
      loop:
        - docker.io
        - docker-compose
        - docker-doc
        - podman-docker
      when: ansible_facts['os_family'] in ["Debian" ]

    - name: Installing Docker (Debian)
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin
      when: ansible_facts['os_family'] in ["Debian" ]

   