---
- name: Postgresql play
  hosts: db_postgres
  gather_facts: false
  vars:
    # optional_vars_file: "{{ lookup('first_found', '.postgres.vars', errors='ignore') }}"
    optional_vars_file: ".postgres.vars"
    psql_db_name: ""
    psql_user_name: ""
    psql_user_password: ""

  tasks:
    # - name: collect facts about system services
    #   ansible.builtin.service_facts:
    #   register: services_state
    # - name: Debug
    #   debug:
    #     var: services_state['ansible_facts']['services']['firewalld.service']

    # - name: Check that the some file exists
    #   ansible.builtin.stat:
    #     path: .postgres.vars
    #   register: result
    # - ansible.builtin.debug:
    #     var: result

    - ansible.builtin.debug:
        var: optional_vars_file

    - name: Loading variables from file if exists
      include_vars: "{{ optional_vars_file }}"
      when: optional_vars_file is file  # exists
    - ansible.builtin.debug:
        var: psql_db_name


    # - name: Installing repo key
    #   ansible.builtin.rpm_key:
    #     key: "{{ zabbix_repo_key }}"
    #     state: present
    #   when: ansible_facts['distribution'] == "CentOS"

    # - name: Installing Zabbix repo
    #   ansible.builtin.dnf:
    #     # name:  "https://repo.zabbix.com/zabbix/6.0/rhel/8/x86_64/zabbix-release-6.0-4.el8.noarch.rpm"
    #     name: "{{ zabbix_repo_rpm }}"
    #     state: present

    # - name: Installing Zabbix agent
    #   ansible.builtin.dnf:
    #     name: zabbix-agent
    #     state: present
