---
- name: Install Redis
  hosts: wt_redis
  gather_facts: false
  vars:
    redis_conf: "/etc/redis/redis.conf"
    redis_service: redis
    redis_password: 12345
    redis_maxmemory: 1000000000
  vars_files:  # Reassign vars
    .wt_redis.vars

  # roles:
  #   - role: wt_redis

  tasks:
    - name: Installing Redis server
      apt:
        name: redis
        state: present

    - name: "Configuring Redis: bind"
      ansible.builtin.lineinfile:
        path: "{{ redis_conf }}"
        regexp: '^bind .*$'
        line: bind 0.0.0.0
        # backup: yes
      notify: Restarting Redis server

    - name: "Configuring Redis: save"
      ansible.builtin.replace:
        path: "{{ redis_conf }}"
        regexp: '^(save .*)$'
        replace: '#\1'
        # backup: yes
      notify: Restarting Redis server

    # - name: "Generaring Redis password"
    #   ansible.builtin.shell:
    #     cmd: "< /dev/urandom tr -dc [:alnum:]_ | head -c 20 ; echo"
    #   register: password

    # - ansible.builtin.debug:
    #     var: password

    - name: "Configuring Redis password"
      ansible.builtin.lineinfile:
        path: "{{ redis_conf }}"
        regexp: '^#* *requirepass .*$'
        line: "requirepass {{ redis_password }}"
        # backup: yes
      notify: Restarting Redis server

    - name: "Configuring Redis maxmemory"
      ansible.builtin.lineinfile:
        path: "{{ redis_conf }}"
        regexp: '^#* *maxmemory '
        line: "maxmemory {{ redis_maxmemory }}"
        # backup: yes
      notify: Restarting Redis server

  handlers:
    - name: Restarting Redis server
      ansible.builtin.systemd:
        name: "{{ redis_service }}"
        state: restarted
        # daemon_reload: yes
