if has("syntax")
  syntax on
endif

set showcmd
set showmatch

set smartcase
set ignorecase
set incsearch
set hlsearch

set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab

if has('persistent_undo')
  set undofile
  set undodir=$HOME/.vim/undo
endif

set directory^=$HOME/.vim/swap//

if has("autocmd")
  au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
endif
