---
# .bashrc
- name: Create .bashrc file
  file:
    path: "{{ bashrc_file }}"
    mode: "0640"
    state: touch
    modification_time: preserve
    access_time: preserve

- name: Setting HISTCONTROL
  lineinfile:
    path: "{{ bashrc_file }}"
    regexp: '^[ #]*HISTCONTROL='
    line: 'HISTCONTROL=ignoreboth:erasedups'

- name: Setting HISTIGNORE
  lineinfile:
    path: "{{ bashrc_file }}"
    regexp: '^[ #]*HISTIGNORE='
    line: 'HISTIGNORE="?:??:$HISTIGNORE"'

- name: Setting HISTSIZE
  lineinfile:
    path: "{{ bashrc_file }}"
    regexp: '^[ #]*HISTSIZE='
    line: 'HISTSIZE=10000'

- name: Setting HISTFILESIZE
  lineinfile:
    path: "{{ bashrc_file }}"
    regexp: '^[ #]*HISTFILESIZE='
    line: 'HISTFILESIZE=5000'

- name: Setting PS1
  lineinfile:
    path: "{{ bashrc_file }}"
    regexp: '^#? ?PS1='
    line: 'PS1="\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\W\[\033[00m\]\$ "'

